# Existing C++ Project
workspace(name = "existing-cpp-project")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# -------------
# | C++ rules |
# -------------

# C++ rules that are probably already in the current WORKSPACE file
# http_archive(
#     name = "rules_cc",
#     urls = ["https://github.com/bazelbuild/rules_cc/releases/download/0.0.9/rules_cc-0.0.9.tar.gz"],
#     sha256 = "2037875b9a4456dce4a79d112a8ae885bbc4aad968e6587dca6e64f3a0900cdf",
#     strip_prefix = "rules_cc-0.0.9",
# )
http_archive(
    name = "rules_cc",
    strip_prefix = "rules_cc-main",
    urls = ["https://github.com/bazelbuild/rules_cc/archive/main.zip"],
)



# Load `cmake_external` rules to build cmake from bazel.
# http_archive(
#     name = "rules_foreign_cc",
#     sha256 = "c2cdcf55ffaf49366725639e45dedd449b8c3fe22b54e31625eb80ce3a240f1e",
#     strip_prefix = "rules_foreign_cc-0.1.0",
#     url = "https://github.com/bazelbuild/rules_foreign_cc/archive/0.1.0.zip",
# )
#
# load("@rules_foreign_cc//:workspace_definitions.bzl", "rules_foreign_cc_dependencies")
#
# # This sets up some common toolchains for building targets. For more details, please see
# # https://github.com/bazelbuild/rules_foreign_cc/tree/main/docs#rules_foreign_cc_dependencies
# rules_foreign_cc_dependencies()
#

# ----------------
# | Python rules |
# ----------------


http_archive(
    name = "rules_python",
    sha256 = "15f84594af9da06750ceb878abbf129241421e3abbd6e36893041188db67f2fb",
    strip_prefix = "rules_python-0.7.0",
    url = "https://github.com/bazelbuild/rules_python/archive/refs/tags/0.7.0.tar.gz",
)

# http_archive(
#     name = "rules_python",
#     sha256 = "778aaeab3e6cfd56d681c89f5c10d7ad6bf8d2f1a72de9de55b23081b2d31618",
#     strip_prefix = "rules_python-0.34.0",
#     url = "https://github.com/bazelbuild/rules_python/releases/download/0.34.0/rules_python-0.34.0.tar.gz",
# )
#
# load("@rules_python//python:repositories.bzl", "py_repositories")
#
# py_repositories()
#
# Setup the workspace for python rules
http_archive(
    name = "bazel_skylib",
    sha256 = "bc283cdfcd526a52c3201279cda4bc298652efa898b10b4db0837dc51652756f",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.7.1/bazel-skylib-1.7.1.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.7.1/bazel-skylib-1.7.1.tar.gz",
    ],
)

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()


# ------------------
# | Pybind11 rules |
# ------------------

# As explained on https://github.com/pybind/pybind11_bazel
http_archive(
    name = "pybind11_bazel",
    strip_prefix = "pybind11_bazel-2.12.0",
    urls = ["https://github.com/pybind/pybind11_bazel/archive/v2.12.0.zip"],
)
# We still require the pybind library.
http_archive(
  name = "pybind11",
  build_file = "@pybind11_bazel//:pybind11-BUILD.bazel",
  strip_prefix = "pybind11-2.12.0",
  urls = ["https://github.com/pybind/pybind11/archive/v2.12.0.zip"],
)
# load("@pybind11_bazel//:python_configure.bzl", "python_configure")
# python_configure(name = "local_config_python")



# # http_archive(
# #   name = "pybind11",
# #   urls = [
# #     "https://github.com/pybind/pybind11/archive/v2.6.0.tar.gz"
# #   ],
# #   sha256 = "90b705137b69ee3b5fc655eaca66d0dc9862ea1759226f7ccd3098425ae69571",
# #   strip_prefix = "pybind11-2.6.0",
# #   build_file = "//:pybind11.BUILD"
# # )
# #
# http_archive(
#   name = "pybind11_bazel",
#   strip_prefix = "pybind11_bazel-34206c29f891dbd5f6f5face7b91664c2ff7185c",
#   urls = ["https://github.com/pybind/pybind11_bazel/archive/34206c29f891dbd5f6f5face7b91664c2ff7185c.zip"],
#   sha256 = "8d0b776ea5b67891f8585989d54aa34869fc12f14bf33f1dc7459458dd222e95",
# )
#
# http_archive(
#   name = "pybind11",
#   build_file = "@pybind11_bazel//:pybind11.BUILD",
#   strip_prefix = "pybind11-a54eab92d265337996b8e4b4149d9176c2d428a6",
#   urls = ["https://github.com/pybind/pybind11/archive/a54eab92d265337996b8e4b4149d9176c2d428a6.tar.gz"],
#   sha256 = "c9375b7453bef1ba0106849c83881e6b6882d892c9fae5b2572a2192100ffb8a",
# )
#
# load("@pybind11_bazel//:python_configure.bzl", "python_configure")
# python_configure(name = "local_config_python")
#
#
